config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import RedirectView

from apps.dendynotdead.views import IndexView, AboutView
from apps.audiofiles.views import ExploreView, SingleView
from apps.news.views import NewsView
from apps.wall.views import WallView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^explore/$', ExploreView.as_view(), name='explore'),
    url(r'^explore/(?P<track_id>\d+)/$', SingleView.as_view(), name='single'),
    url(r'^news/$', RedirectView.as_view(url='/news/1/')),
    url(r'^news/(?P<page_id>\d+)/$', NewsView.as_view(), name='news'),
    url(r'^wall/$', WallView.as_view(), name='wall'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/audiofiles/models.py
from datetime import datetime

from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from . import AUDIO_VERSION


class AudioFile(models.Model):
    file_mp3 = models.URLField(
        blank=True,
        max_length=256,
        verbose_name=_('Audio File URL (MP3)'),
    )
    file_ogg = models.URLField(
        blank=True,
        max_length=256,
        verbose_name=_('Audio File URL (OGG)'),
    )
    file_wav = models.URLField(
        blank=True,
        max_length=256,
        verbose_name=_('Audio File URL (WAV)'),
    )
    version = models.CharField(
        max_length=3,
        choices=AUDIO_VERSION,
        default=AUDIO_VERSION[0],
        verbose_name=_('Audio Type'),
    )
    main_priority = models.BooleanField(
        default=False,
        verbose_name=_('Main priority')
    )
    parent_track = models.ForeignKey(
        null=True,
        to='AudioTrack',
        verbose_name=_('Related Audio Track'),
    )

    def __str__(self):
        return '{0} ({1})'.format(
            self.parent_track.track_name,
            self.version
        )

    def clean(self):
        """Custom clean method."""
        files = (self.file_ogg, self.file_wav, self.file_mp3)
        if not any(files):
            raise ValidationError(_(
                'At least one of the files should be uploaded'
            ))


class AudioTrack(models.Model):
    artist = models.CharField(
        max_length=128,
        default=_('Dendy Not Dead'),
        verbose_name=_('Artist'),
    )
    track_name = models.CharField(
        max_length=256,
        verbose_name=_('Track Name'),
    )
    description_ru = models.TextField(
        null=True,
        blank=True,
        verbose_name=_('Russian description'),
    )
    description_en = models.TextField(
        null=True,
        blank=True,
        verbose_name=_('English description'),
    )
    lyrics = models.TextField(
        null=True,
        blank=True,
        verbose_name=_('Lyrics'),
    )
    published = models.DateField(
        null=True,
        blank=True,
        verbose_name=_('Publication date')
    )
    gtp_file = models.FileField(
        null=True,
        blank=True,
        verbose_name=_('GuitarPro File'),
        upload_to='gtp'
    )
    youtube_link = models.URLField(
        null=True,
        blank=True,
        verbose_name=_('YouTube link')
    )
    likes = models.IntegerField(
        default=0,
        verbose_name=_('likes')
    )

    def inc_like(self):
        """Method to increment `likes` attribute."""
        self.likes += 1

    @property
    def was_published(self):
        """Property to get message - when track was published."""
        delta = (datetime.now().date() - self.published).days
        if delta == 0:
            return _('This track was published today!')
        else:
            return _('This track was published {0} days ago'.format(delta))

    @property
    def brand_new_track(self):
        """Property to check is brand new."""
        delta = (datetime.now().date() - self.published).days
        if delta < settings.BRAND_NEW_TRACK_DAYS:
            return True

    @property
    def short_name(self):
        """Property to get short name of track."""
        if len(self.track_name) > 25:
            return self.track_name[:25] + '...'
        else:
            return self.track_name

    def __str__(self):
        """String representation of audio track."""
        return '{0} — {1}'.format(self.artist, self.track_name)

templates/components/footer.html
<div class="ui black inverted vertical footer site-footer segment">
  <br>
  <div class="ui container transparent">
    <div class="ui stackable inverted grid">
      <div class="five wide column">
        <div class="ui list">
          <div class="item">
            <i class="refresh icon"></i>
            <div class="content" id="change-lang">
              <a class="white-link" href="#">Change language</a>
            </div>
          </div>
          <div class="item">
            <i class="users icon"></i>
            <div class="content">
              <a class="white-link" href="#">Denis Krumko</a>
            </div>
          </div>
          <div class="item">
            <i class="marker icon"></i>
            <div class="content">
              <a class="white-link" href="https://goo.gl/dkg4AM" target="_blank">Krasnoyarsk, RUS</a>
            </div>
          </div>
          <div class="item">
            <i class="mail icon"></i>
            <div class="content">
              <a class="white-link" href="mailto:dendynotdead@gmail.com">dendynotdead@gmail.com</a>
            </div>
          </div>
          <div class="item">
            <i class="linkify icon"></i>
            <div class="content white-text">
              <a class="white-link" href="http://youtube.com" target="_blank">dendynotdead.com</a>
            </div>
          </div>
  </div>
      </div>
      <div class="three wide column">

      </div>
    </div>
    <br>
<div class="credentials-center">
  © 2017 Dendy Not Dead, Inc.
</div>
  </div>

  <br>
</div>

templates/components/menu.html
<div class="ui secondary pointing menu mymenu {% if inverted %}inverted menu-noborder {% endif %}mobile-hidden-menu">
  <div class="myicon">
    <div class="square s-red"></div>
    <div class="square s-red"></div>
    <div style='clear:both'></div>
    {% if inverted %}
      <div class="square s-grey"></div>
      <div class="square s-grey"></div>
    {% else %}
      <div class="square s-black"></div>
      <div class="square s-black"></div>
    {% endif %}
  </div>
  <a href="/" class="item">
    Home
  </a>
  <a href="/news/1" class="item {% if menu_section == 'news' %}active{% endif%}">
    News
  </a>
  <a href="/explore" class="item {% if menu_section == 'explore' %}active{% endif%}">
    Explore
  </a>
  <a href="/wall" class="item {% if menu_section == 'wall' %}active{% endif%}">
    The Wall
  </a>
  <div class="right menu">
    <a href="/about" class="ui item {% if menu_section == 'about' %}active{% endif%}">
      About
    </a>
  </div>
</div>
<div class="ui secondary pointing menu mymenu {% if inverted %}inverted {% endif %}mobile-show-menu">
  <div class="myicon">
    <div class="square s-red"></div>
    <div class="square s-red"></div>
    <div style='clear:both'></div>
    {% if inverted %}
      <div class="square s-grey"></div>
      <div class="square s-grey"></div>
    {% else %}
      <div class="square s-black"></div>
      <div class="square s-black"></div>
    {% endif %}
  </div>
  {% if menu_section == 'explore' %}
    <a href="/explore/" class="item active">
      Explore
    </a>
  {% endif %}
  {% if menu_section == 'news' %}
    <a href="/news/1/" class="item active">
      News
    </a>
  {% endif %}
  {% if menu_section == 'wall' %}
    <a href="/wall/" class="item active">
      The Wall
    </a>
  {% endif %}
  {% if menu_section == 'about' %}
    <a href="/wall/" class="item active">
      About...
    </a>
  {% endif %}
  <div class="right menu">
    <div class="item">
      <div class="ui down dropdown">
        <i class="sidebar icon"></i>
        <div class=" menu">
          <a href="/" class="{% if menu_section == 'home' %}active noborder{% endif%} item">
            <i class="home icon"></i>Home
          </a>
          <a href="/news" class="{% if menu_section == 'news' %}active noborder{% endif%} item">
            <i class="newspaper icon"></i>News
          </a>
          <a href="/explore" class="{% if menu_section == 'explore' %}active noborder{% endif%} item">
            <i class="music icon"></i>Explore
          </a>
          <a href="/wall" class="{% if menu_section == 'wall' %}active noborder{% endif%} item">
            <i class="talk icon"></i>The Wall
          </a>
          <a href="/about" class="{% if menu_section == 'about' %}active noborder{% endif%} item">
            <i class="help icon"></i>About
          </a>
        </div>
      </div>
</div>


  </div>
</div>

templates/components/right_rail.html
<div class="right ui rail rail-hidden">
  <div class="ui sticky fixed top">
    <h4 class="ui header">
      Explore tracks
    </h4>
    <div class="ui vertical fluid accordion text menu">
      <div class="item">
        <a class="title">
          <i class="dropdown icon"></i>
          <b>Dendy Not Dead</b>
        </a>
        <div class="content menu">
          {% for track in dnd_tracks %}
          <a class="item" href="#track_{{ track.id }}">
            {{ track.track_name }}
          </a>
          {% endfor %}
        </div>
      </div>
      <div class="item">
        <a class="title">
          <i class="dropdown icon"></i>
          <b>Deniska Krumko</b>
        </a>
        <div class="content menu">
          {% for track in dk_tracks %}
          <a class="item" href="#track_{{ track.id }}">
            {{ track.track_name }}
          </a>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

templates/components/tracks_info.html
{% load static %}

<div class="ui items" >
  {% for track in tracks %}

  <div class="item track-item" id="track_{{ track.id }}">
    <!-- Track Round Image -->
    <div class="ui small circular image explore-round">
        <img src="{% static 'images/image.png' %}">
    </div>

    <!-- Track Content -->
    <div class="content track-content">

      <!-- Track Name (not mobile) -->
      <a href="{{ track.id }}" class="track-name track-name-base header mobile-hidden">
        {{ track.track_name }}
      </a>
      <!-- Track Name (mobile) -->
      <a href="{{ track.id }}" class="track-name header mobile-show">
        {{ track.track_name }}
      </a>
      <!-- New song label -->
      {% if track.brand_new_track %}
      <span class="ui red label mobile-hidden new-song-label default-cursor">
        <i class="star icon"></i>
        New track!
      </span>
      {% endif %}
      <!-- Track Artist -->
      <div class="meta">
          <span>{{ track.artist }}</span>
      </div>
      <!-- Track Audio File -->
      <div class="description">
        <audio controls preload="metadata">
          {% for a in track.audiofile_set.all %}
          <source src="{{ a.audio_file_url }}"
                  type="{{ a.audio_mimetype }}">
          {% endfor %}
          <p> Your browser does not support the audio element. </p>
        </audio>
      </div>
      <!-- Track Links -->
      <div class="extra">
        <!-- Published -->
        {% if track.published %}
          <span class="track_link default-cursor">
            <i class="calendar icon"></i>{{ track.published }}
          </span>
        {% endif %}
        <!-- Guitar Pro File -->
        {% if track.gtp_file %}
        <a href="{{ track.gtp_file.url }}" class="gtp_link track_link mobile-hidden-link">
          <i class="user icon"></i> GTP File
        </a>
        {% endif %}
        <!-- YouTube -->
        {% if track.youtube_link %}
        <a href="{{ track.youtube_link }}" class="youtube_link track_link mobile-hidden-link">
          <i class="youtube play icon"></i> YouTube
        </a>
        {% endif %}
        <!-- Likes -->
        <span class="right floated track_link noselect">
          <i onClick="myFunction(this.id)"
             id="{{ track.id }}"
             class="like icon">
            <input style="display: none;" type="submit" value="LIKE">
          </i>
          <label id="number{{ track.id }}" class="default-cursor">
            {{ track.likes }}
          </label>
           <span class="default-cursor">
             likes
           </span>
        </span>
      </div>
    </div>
  </div>
  <!-- Track Divider -->
  <div class="ui divider"></div>

{% endfor %}
</div>